TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""

TWITTER_ACCESS_TOKEN_KEY = "0"
TWITTER_ACCESS_TOKEN_SECRET = ""

GET_TWEET_COUNT = 10

TELEGRAM_API_ID = 0
TELEGRAM_API_HASH = ''

REDDIT_CLIENT_ID = ""
REDDIT_CLIENT_SECRET = ""
REDDIT_PASSWORD = ""
REDDIT_USER_AGENT = ""
REDDIT_USERNAME = ""

KAFKA_CONNECTION_URL = ""